[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20000
via_ir = true
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@chainlink/contracts-ccip/=lib/ccip-contracts/contracts-ccip/',
]
fs_permissions = [{ access = "read", path = "./" }]
evm_version = "cancun"
solc = "0.8.25"
[etherscan]
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=421614" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
